psiu2/urls.py
from django.contrib import admin
from django.urls.conf import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('psiuApp.urls')),
]

psiuApp/urls.py
from django.urls import reverse_lazy
from django.urls.conf import path 
from psiuApp import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.models import User 
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView 
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView 

app_name = "psiuApp"

urlpatterns = [
    path('criaAtividade/<str:tipo>', views.AtividadeCreateView.as_view(), name='cria-atividade'),
    path('listaAtividades/<str:tipo>', views.AtividadeListView.as_view(), name='lista-atividades'), 
    path('atualiza/<int:pk>/', views.AtividadeUpdateView.as_view(), name='atualiza-atividade'),
    path('apaga/<int:pk>/', views.AtividadeDeleteView.as_view(), name='apaga-atividade'), 
    path('', views.home, name='homepage'), 
    path('atividade/<int:pk>', views.AtividadeView.as_view(), name='atividade'), 
    path('perfil/<int:pk>', views.PerfilView.as_view(), name='perfil'), 
    path('participa_atividade/<int:pk>', views.AtividadeParticipaView.as_view(), name='participa-atividade'),

    #Autenticação
    path('registro/', views.registro, name='registro'),
    path('login/', LoginView.as_view(template_name='psiuApp/login.html', next_page=reverse_lazy('psiuApp:homepage')), name='login'),
    path('logout_usuario/', views.logout, name='logout_usuario'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('psiuApp:homepage'),), name='logout'),
    path('trocar_senha/', PasswordChangeView.as_view(template_name='psiuApp/trocar_senha.html', success_url=reverse_lazy('psiuApp:trocar_senha_finalizado'),), 
                                                        name='trocar_senha'), 
    path('trocar_senha_finalizado/',PasswordChangeDoneView.as_view(template_name='psiuApp/trocar_senha_finalizado.html', ), name='trocar_senha_finalizado'), 
    path('editar_perfil/<int:pk>/', views.PsiuAppUpdateView.as_view(template_name='psiuApp/editar_perfil.html', 
                                                                   success_url=reverse_lazy('psiuApp:homepage'), model=User, fields=['first_name', 'last_name', 'email',], ), 
                                                                   name='editar-perfil'),

    path('reset_password/', PasswordResetView.as_view(
        template_name='psiuApp/reset_senha.html',
        email_template_name='psiuApp/password_reset_email.html',
        success_url=reverse_lazy('psiuApp:password_reset_done'),
        #html_email_template_name='psiuApp/password_reset_email.html',
        subject_template_name='psiuApp/password_reset_subject.txt',
        from_email='noreply@psiuapp.com.br',
    ), name='reset_password'), 
    path('reset_password_sent/', PasswordResetDoneView.as_view(template_name='psiuApp/reset_senha_enviado.html',), name='password_reset_done'), 
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='psiuApp/reset_nova_senha.html',  
                                                                                            success_url=reverse_lazy('psiuApp:password_reset_complete'),), name='password_reset_confirm'), 
    path('reset_password_complete/', PasswordResetCompleteView.as_view(template_name='psiuApp/reset_completo.html'), name='password_reset_complete'), 
] 

psiuApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Atividade(models.Model):
  id = models.AutoField(primary_key=True)

  #Todas as atividades
  criador = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
  vagas = models.PositiveIntegerField(default=4)
  adicionais = models.CharField(verbose_name='Observações', max_length=254, blank=True, default='')
  data = models.DateField(auto_now_add=False)
  hora = models.TimeField(auto_now_add=False)

class Carona(Atividade):
  localSaida = models.CharField(verbose_name='Saindo de', max_length=30)
  localChegada = models.CharField(verbose_name='Destino', max_length=30)

class Extracurriculares(Atividade):
  atividade = models.CharField(max_length=30)
  local = models.CharField(max_length=30)

class Estudos(Atividade):
  materia = models.CharField(verbose_name='Disciplina', max_length=10)
  local = models.CharField(max_length=30)

class Liga(Atividade):
  nome = models.CharField(verbose_name='Nome da Liga', max_length=30)
  local = models.CharField(max_length=30)

class ConhecerPessoas(Atividade):
  atividade = models.CharField(max_length=30)
  local = models.CharField(max_length=30)

class ParticipaAtividade(models.Model):
  participante = models.ForeignKey(User, on_delete=models.CASCADE)
  atividade = models.ForeignKey(Atividade, on_delete=models.CASCADE)

psiuApp/forms.py
from datetime import datetime
from django import forms 
from psiuApp.models import Carona, Extracurriculares, Estudos, Liga, ConhecerPessoas


widgets_data_hora = { 
            'data': forms.TextInput(attrs={'type': 'date',}, ),
            'hora': forms.TextInput(attrs={'type': 'time',}, ),
        }

def clean_generico(self):
    data = self.cleaned_data.get('data')
    hora = self.cleaned_data.get('hora')
    
    datetime_atividade = datetime.combine(data, hora)
    if datetime_atividade < datetime.now():
        if data < datetime.now().date():
            self._errors['data'] = self.error_class([
                'O evento não pode já ter ocorrido!'])
        else:
            self._errors['hora'] = self.error_class([
                'O evento não pode já ter ocorrido!'])

    return self.cleaned_data


class CaronaModel2Form(forms.ModelForm):
    class Meta:
        model = Carona 
        fields = ['localSaida','localChegada','data','hora','vagas','adicionais']
        widgets = widgets_data_hora

    def clean(self):
        super(CaronaModel2Form, self).clean()
        return clean_generico(self)
        

class ExtracurricularesModel2Form(forms.ModelForm):
    class Meta:
        model = Extracurriculares 
        fields = ['atividade','local','data','hora','vagas','adicionais']
        widgets = widgets_data_hora
    
    def clean(self):
        super(ExtracurricularesModel2Form, self).clean()
        return clean_generico(self)

class EstudosModel2Form(forms.ModelForm):
    class Meta:
        model = Estudos 
        fields = ['materia','local','data','hora','vagas','adicionais']
        widgets = widgets_data_hora
    
    def clean(self):
        super(EstudosModel2Form, self).clean()
        return clean_generico(self)

class LigasModel2Form(forms.ModelForm):
    class Meta:
        model = Liga 
        fields = ['nome','local','data','hora','vagas','adicionais']
        widgets = widgets_data_hora
    
    def clean(self):
        super(LigasModel2Form, self).clean()
        return clean_generico(self)

class ConhecerPessoasModel2Form(forms.ModelForm):
    class Meta:
        model = ConhecerPessoas 
        fields = ['atividade','local','data','hora','vagas','adicionais']
        widgets = widgets_data_hora
    
    def clean(self):
        super(ConhecerPessoasModel2Form, self).clean()
        return clean_generico(self)

psiuApp/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.base import View 
from psiuApp.forms import CaronaModel2Form, EstudosModel2Form, ExtracurricularesModel2Form, ConhecerPessoasModel2Form, LigasModel2Form
from psiuApp.models import Atividade
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required 
from django.views.generic.edit import UpdateView 
from django.contrib.auth.models import User
from psiuApp.models import Carona, Estudos, Extracurriculares, ConhecerPessoas, Liga, ParticipaAtividade
from django.contrib.auth import authenticate, login
from datetime import datetime

listaAtividades = ['carona', 'estudos', 'ligas', 'extracurriculares', 'conhecer_pessoas']
nomeAtividade = {'carona': 'Carona', 
                 'estudos': 'Grupo de Estudos', 
                 'ligas': 'Ligas Acadêmicas', 
                 'extracurriculares': 'Atividades Extracurriculares', 
                 'conhecer_pessoas': 'Conhecer Pessoas'}

def tipoAtividadeForm(tipo: str):
    if tipo == 'carona':
        return CaronaModel2Form
    elif tipo == 'estudos':
        return EstudosModel2Form
    elif tipo == 'extracurriculares':
        return ExtracurricularesModel2Form
    elif tipo == 'ligas':
        return LigasModel2Form
    elif tipo == 'conhecer_pessoas':
        return ConhecerPessoasModel2Form
    return None

def tipoAtividadeModel(tipo: str):
    if tipo == 'carona':
        return Carona
    elif tipo == 'estudos':
        return Estudos
    elif tipo == 'extracurriculares':
        return Extracurriculares
    elif tipo == 'ligas':
        return Liga
    elif tipo == 'conhecer_pessoas':
        return ConhecerPessoas
    return None

def get_atividade(pk: int):
    tipos_atividades = [Carona, Liga, Extracurriculares, Estudos, ConhecerPessoas]
    for tipo in tipos_atividades:
        try:
            atividade = tipo.objects.get(pk=pk) 
            return atividade
        except:
            pass
        
    return None

def get_atividade_type(atividade):
    atividade = get_atividade(atividade)
    if type(atividade) == Carona:
        return 'carona'
    if type(atividade) == Estudos:
        return 'estudos'
    if type(atividade) == Extracurriculares:
        return 'extracurriculares'
    if type(atividade) == Liga:
        return 'ligas'
    if type(atividade) == ConhecerPessoas:
        return 'conhecer_pessoas'
    return None

def get_imagem_atividade(tipo: str):
    return 'psiuApp/img/' + tipo + '.png'

def remove_atividades_expiradas():
    atividades = Atividade.objects.all()

    for atividade in atividades:
        datetime_atividade = datetime.combine(atividade.data, atividade.hora)
        if datetime_atividade < datetime.now():
            participantes_atividade = ParticipaAtividade.objects.filter(atividade=atividade)
            for participante in participantes_atividade:
                participante.delete()
            atividade.delete()


# Create your views here.
def home(request): 
    # processamento antes de mostrar a home page 
    return render(request, 'psiuApp/home.html') 

def days_hours_minutes(td):
    return {'dias': td.days, 'horas': td.seconds//3600, 'minutos': (td.seconds//60)%60}

class AtividadeView(View): 
    def get(self, request, pk, *args, **kwargs): 
        
        remove_atividades_expiradas()

        atividade = get_atividade(pk)
        if atividade is None:
            return redirect('psiuApp:homepage')
        
        #Verifica se o usuário participa da atividade
        botaoParticipar = False
        if request.user.is_authenticated:
            usuario_participa = ParticipaAtividade.objects.filter(atividade=Atividade.objects.get(pk=pk), participante=request.user)
            if len(usuario_participa) == 0:
                botaoParticipar = True

        #Lista de participantes
        participantes = ParticipaAtividade.objects.filter(atividade=Atividade.objects.get(pk=pk))
        tipo_atividade = get_atividade_type(atividade)
        
        datetime_atividade = datetime.combine(atividade.data, atividade.hora)

        tempo_ate_atividade = datetime_atividade - datetime.now()
        
        contexto = {'atividade': atividade, 
                    'botaoParticipar': botaoParticipar, 
                    'participantes': participantes, 
                    'tipoAtividade': tipo_atividade,
                    'nomeAtividade': nomeAtividade.get(tipo_atividade, 'Não existente'),
                    'tempoAteAtividade': days_hours_minutes(tempo_ate_atividade),
                    'imagem_atividade': get_imagem_atividade(tipo_atividade)}

        return render( 
            request,  
            'psiuApp/atividade.html',  
            contexto) 

class AtividadeParticipaView(View): 
    def get(self, request, pk, *args, **kwargs):  
        atividade = get_atividade(pk)
        tipo_atividade = get_atividade_type(atividade)

        if atividade is None:
            return HttpResponseRedirect(reverse_lazy("psiuApp:homepage"))
        
        participantes = ParticipaAtividade.objects.filter(atividade=Atividade.objects.get(pk=pk), participante=request.user)

        if len(participantes) == 0:
            if atividade.vagas > 0:
                participacao = ParticipaAtividade(atividade=Atividade.objects.get(pk=pk), participante=request.user)
                participacao.save()

                atividade.vagas -= 1
                atividade.save()
        else:
            atividade.vagas += len(participantes)
            atividade.save()
            for participante in participantes:
                participante.delete()

        return HttpResponseRedirect(reverse_lazy("psiuApp:atividade", args=[pk,]))


class PerfilView(View): 
    def get(self, request, pk, *args, **kwargs): 
        
        #Verifica se esse usuário existe
        try:
            perfil = User.objects.get(pk=pk) 
        except:
            return redirect('psiuApp:homepage')
        
        atividades_criadas = []
        for tipo_atividade in listaAtividades:
            atividades = tipoAtividadeModel(tipo_atividade).objects.filter(criador=pk)
            for atividade in atividades:
                atividade.tipo = tipo_atividade
            atividades_criadas.extend(atividades)
    
        #Pega atividades que usuário participa
        participacoes = ParticipaAtividade.objects.filter(participante=pk)
        atividades_participa = []
        for participa in participacoes:
            atividade = get_atividade(participa.atividade.id)
            atividade.tipo = get_atividade_type(atividade)
            atividades_participa.append(atividade)


        contexto = {'atividades_criadas': atividades_criadas, 'atividades_participa': atividades_participa, 'perfil': perfil,} 

        return render( 
            request,  
            'psiuApp/perfil.html',  
            contexto) 


class AtividadeListView(View): 
    def get(self, request, tipo, *args, **kwargs): 
        
        remove_atividades_expiradas()

        if tipo not in listaAtividades:
            return redirect('psiuApp:homepage') 
        
        atividades = tipoAtividadeModel(tipo).objects.all()
        for atividade in atividades:
            atividade.tipo = tipo

        contexto = { 'atividades': atividades, 'tipoAtividade': tipo, 'nomeAtividade': nomeAtividade.get(tipo, 'Não existente'), 'imagem_atividade': get_imagem_atividade(tipo)} 

        return render( 
            request,  
            'psiuApp/listaAtividades.html',  
            contexto) 

class AtividadeCreateView(LoginRequiredMixin, View): 
    def get(self, request, tipo, *args, **kwargs): 

        if tipo not in listaAtividades:
            return redirect('psiuApp:homepage') 
        
        contexto = { 'formulario': tipoAtividadeForm(tipo), 
                    'tipoAtividade': tipo, 
                    'nomeAtividade': nomeAtividade.get(tipo, 'Não existente'), 
                    'imagem_atividade': get_imagem_atividade(tipo)} 
        
        return render(request, "psiuApp/criaAtividade.html", contexto) 
    
    def post(self, request, tipo, *args, **kwargs):
        formulario = tipoAtividadeForm(tipo)(request.POST)
        if formulario.is_valid():
            atividade = formulario.save()
            atividade.criador = request.user
            atividade.save() 
            return HttpResponseRedirect(reverse_lazy("psiuApp:lista-atividades", args=[tipo,])) 
        else:
            contexto = { 'formulario': formulario, 
                    'tipoAtividade': tipo, 
                    'nomeAtividade': nomeAtividade.get(tipo, 'Não existente'), 
                    'imagem_atividade': get_imagem_atividade(tipo)} 
        
            return render(request, "psiuApp/criaAtividade.html", contexto) 


class AtividadeUpdateView(LoginRequiredMixin, View): 
    def get(self, request, pk, *args, **kwargs):
        tipo_atividade = get_atividade_type(get_atividade(pk))
        atividade = tipoAtividadeModel(tipo_atividade).objects.get(pk=pk) 

        if atividade.criador != request.user:
            return HttpResponseRedirect(reverse_lazy("psiuApp:homepage"))

        formulario = tipoAtividadeForm(tipo_atividade)(instance=atividade)

        context = {'formulario': formulario, 
                   'nomeAtividade': nomeAtividade.get(tipo_atividade, 'Não existente'), 
                   'pk_atividade': pk, 
                   'imagem_atividade': get_imagem_atividade(tipo_atividade)} 
        

psiuApp/templates/psiuApp/atividade.html
{% extends 'psiuApp/base.html' %}
{% load static %} 

{% block content %}

<div class="container text-center">
    <br>
    <img src="{% static imagem_atividade %}" alt="Imagem da atividade">
    <h4 class="text-center lh-sm">{{ nomeAtividade }}</h4>
</div>

<br>
<a type="button" class="btn btn-primary ml-3" href="{% url 'psiuApp:lista-atividades' tipo=tipoAtividade %}"><i class="fa fa-arrow-left" aria-hidden="true"></i> Voltar</a>

{% if tipoAtividade == 'carona' %}
<h4 class="text-center negrito"><b>Destino:</b> {{ atividade.localChegada }}</h4>
<h4 class="text-center negrito"><b>Saindo de:</b> {{ atividade.localSaida }}</h4>
{% elif tipoAtividade == 'estudos' %}
<h4 class="text-center negrito"><b>Disciplina:</b> {{ atividade.materia }}</h4>
{% elif tipoAtividade == 'extracurriculares' %}
<h4 class="text-center negrito"><b>Atividade:</b> {{ atividade.atividade }}</h4>
{% elif tipoAtividade == 'ligas' %}
<h4 class="text-center negrito"><b>Liga:</b> {{ atividade.nome }}</h4>
{% elif tipoAtividade == 'conhecer_pessoas' %}
<h4 class="text-center negrito"><b>Atividade:</b> {{ atividade.atividade }}</h4>
{% endif %}

{% if tipoAtividade != 'carona' %}
<h4 class="text-center negrito"><b>Local:</b> {{ atividade.local }}</h4>
{% endif %}

<br>

<div class="text-center">
    <h4><b>Data:</b> {{ atividade.data }} - <b>Hora:</b> {{ atividade.hora }}</h4>
    <h4><b>Em:</b> {{ tempoAteAtividade.dias }}d {{ tempoAteAtividade.horas }}h {{ tempoAteAtividade.minutos }}m</h4>
</div>

<br>
<div class="text-center">
    <h4><b>Criado por:</b> {{ atividade.criador.username }} <a class="btn btn-info" type="button" href="{% url 'psiuApp:perfil' pk=atividade.criador.id %}"><i class="fa fa-user-circle" aria-hidden="true"></i></a></h4>
    <br>
    {% if atividade.adicionais %}
        <h4><b>Observações</b></h4>
        <p>{{ atividade.adicionais }}</p>
    {% endif %}
    <br>
    <div>
        <h4><b>Participantes</b> - <b>Vagas:</b> {{ atividade.vagas }}</h4>
        {% for participante in participantes %}
            {{ participante.participante.username }} <a class="btn btn-info" type="button" href="{% url 'psiuApp:perfil' pk=participante.participante.id %}"><i class="fa fa-user-circle" aria-hidden="true"></i></a>
        {% empty %}
            <h6>Ainda não há participantes cadastrados nessa atividade</h6>
        {% endfor %}
        <div>
            <br>
            {% if user != atividade.criador %}
                {% if user.is_authenticated %}
                    {% if botaoParticipar == True %}
                        {% if atividade.vagas > 0 %}
                            <a type="button" class="btn btn-primary ml-3" href="{% url 'psiuApp:participa-atividade' pk=atividade.id %}">Participar</a>
                        {% endif %}
                    {% else %}
                    <a type="button" class="btn btn-danger ml-3" href="{% url 'psiuApp:participa-atividade' pk=atividade.id %}">Cancelar Participação</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

{% if user == atividade.criador %}
    <div class="container text-center">
        <br>
        <a type="button" class="btn btn-warning ml-3" href="{% url 'psiuApp:atualiza-atividade' pk=atividade.id %}">Editar Atividade</a>
        <a type="button" class="btn btn-danger ml-3" href="{% url 'psiuApp:apaga-atividade' pk=atividade.id %}">Apagar Atividade</a>
    </div>
{% endif %}

{% endblock %}

psiuApp/templates/psiuApp/atualizaAtividade.html
{% extends 'psiuApp/base.html' %}

{% load static %} 
{% load crispy_forms_tags %}

{% block content %} 
  <div class="container text-center">
    <br>
    <img src="{% static imagem_atividade %}" alt="Imagem da atividade">
    <h4 class="text-center lh-sm">Atualização de atividade: {{ nomeAtividade }}</h4>
  </div>
  <div class="container text-center tam-formulario">
    <form method="POST"> 
        {% csrf_token %}
        {{ formulario|crispy }} 
        <a type="button" class="btn btn-danger ml-3" href="{% url 'psiuApp:atividade' pk=pk_atividade %}">Cancelar</a> 
        <button type="submit" class="btn btn-success ">Atualizar</button>
    </form> 
  </div>
{% endblock %}

psiuApp/templates/psiuApp/cards_personalizados.html
<div class="card border-dark mb-3" style="width: 18rem;">
    <div class="card-body">

        {% if atividade.tipo == 'carona' %}
            <h5 class="card-title">Destino: {{ atividade.localChegada }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Saindo de: {{ atividade.localSaida }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Vagas: {{ atividade.vagas }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ atividade.data }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Horário: {{ atividade.hora }}</h6>
        {% elif atividade.tipo == 'estudos' %}
            <h5 class="card-title">Matéria: {{ atividade.materia }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Local: {{ atividade.local }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Vagas: {{ atividade.vagas }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ atividade.data }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Horário: {{ atividade.hora }}</h6>
        {% elif atividade.tipo == 'extracurriculares' %}
            <h5 class="card-title">Atividade: {{ atividade.atividade }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Local: {{ atividade.local }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Vagas: {{ atividade.vagas }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ atividade.data }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Horário: {{ atividade.hora }}</h6>
        {% elif atividade.tipo == 'ligas' %}
            <h5 class="card-title">Liga: {{ atividade.nome }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Local: {{ atividade.local }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Vagas: {{ atividade.vagas }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ atividade.data }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Horário: {{ atividade.hora }}</h6>
        {% elif atividade.tipo == 'conhecer_pessoas' %}
            <h5 class="card-title">Atividade: {{ atividade.atividade }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Local: {{ atividade.local }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Vagas: {{ atividade.vagas }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Data: {{ atividade.data }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Horário: {{ atividade.hora }}</h6>
        {% endif %}
        <a href="{% url 'psiuApp:atividade' pk=atividade.id %}" class="btn btn-primary">Mais informações</a>
    </div>
</div>

psiuApp/templates/psiuApp/criaAtividade.html
{% extends 'psiuApp/base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}

{% block content %} 

<div class="container text-center">
  <br>
  <img src="{% static imagem_atividade %}" alt="Imagem da atividade">
  <h4 class="text-center lh-sm">Criação de atividade: {{ nomeAtividade }}</h4>
</div>
<br>
<div class="container text-center tam-formulario">
  <form action="" method="POST" class="text-center"> 
    {% csrf_token %} 
    {{ formulario|crispy }} 
    <a type="button" class="btn btn-danger ml-3" href="{% url 'psiuApp:lista-atividades' tipo=tipoAtividade %}">Cancelar</a> 
    <button type="submit" class="btn btn-success ">Cria Atividade</button>
  </form> 
</div>
{% endblock %}

psiuApp/templates/psiuApp/header.html
<a href="/"> 
    Home-Page 
  </a> | 
  <a href="{% url 'psiuApp:lista-atividades' %}"> 
    Listar contatos 
  </a> |
  <a href="{% url 'psiuApp:cria-atividade' %}"> 
    Cria atividade 
  </a> | </a> 
  {% if not user.is_authenticated %} 
    <a href="{% url 'psiuApp:registro' %}">Registrar</a> |
    <a href="{% url 'psiuApp:login' %}">Login</a> |
  {% else %}
    <a href="{% url 'psiuApp:logout_usuario' %}">Logout</a> |
    <a href="{% url 'psiuApp:password_change' %}">Trocar senha</a> |
    <a href="{% url 'psiuApp:completaDadosUsuario' pk=user.id %}">Terminar registro</a> |
  {% endif %}
    Você é {% firstof user.username "visitante" %} |
  <hr>

psiuApp/templates/psiuApp/listaAtividades.html
{% extends 'psiuApp/base.html' %}
{% load static %} 

{% block content %}

<div class="container text-center">
    <br>
    <img src="{% static imagem_atividade %}" alt="Imagem da atividade">
    <h4 class="text-center lh-sm">{{ nomeAtividade }}</h4>
</div>

<a type="button" class="btn btn-primary ml-3" href="{% url 'psiuApp:cria-atividade' tipo=tipoAtividade %}">Criar Nova Atividade</a>
<br>
<br>
<div class="container text-center">
    <div class="row justify-content-center">
        {% for atividade in atividades %}
            <div class="col-auto">
                {% include 'psiuApp/cards_personalizados.html' %}
            </div>
        {% empty %} 
            <h2 class="negrito text-center">Não há atividades cadastradas</h2>
        {% endfor %} 
    </div>
</div>

{% endblock %}

psiuApp/templates/psiuApp/password_reset_email.html

Ei Psiu!

Alguém solicitou em a redefinição da sua senha!
 
Por favor, acesse a seguinte página e escolha uma nova senha:
{% url 'psiuApp:password_reset_confirm' uidb64=uid token=token as link %} 
{{ protocol}}://{{ domain }}{{ link }}
 
Seu nome de usuário, caso tenha esquecido: {{ user }}
 
Obrigado por usar nosso site!
 
Equipe Psiu!

psiuApp/templates/psiuApp/reset_completo.html
{% extends 'psiuApp/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Senha Nova Criada{% endblock %} 
{% block content %} 

{% include 'psiuApp/greeting_psiu.html' %}
<h4 class="text-center lh-sm">Sua nova senha foi criada!</h4>
<br>
<div class="container text-center">
    <a type="button" class="btn btn-success ml-3" href="{% url 'psiuApp:login' %}">Fazer Login</a> 
</div>
{% endblock %} 